plugins {
    id 'java'
}

group = 'com.saucedemo'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    seleniumVersion = '4.49.0'
    cucumberVersion = '7.34.8'
    webDriverManagerVersion = '6.3.4'
}

dependencies {

    // Selenium
    testImplementation "org.seleniumhq.selenium:selenium-java:${seleniumVersion}"

    // WebDriverManager
    testImplementation "io.github.bonigarcia:webdrivermanager:${webDriverManagerVersion}"

    // Cucumber
    testImplementation "io.cucumber:cucumber-java:${cucumberVersion}"
    testImplementation "io.cucumber:cucumber-junit-platform-engine:${cucumberVersion}"

    // JUnit
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // JUnit Platform
    testImplementation 'org.junit.platform:junit-platform-suite'
}

test {
    useJUnitPlatform()
}